-- Seleccionar campos para nueva tabla PRODUCT
-- Pendiente: PRODUCT ID y LOADING_DATE
SELECT
    P.NAME AS PRODUCT_NAME,
    P.COLOR AS PRODUCT_COLOR,
    PS.NAME AS PRODUCT_SUBCATEGORY,
    PC.NAME AS PRODUCT_CATEGORY
FROM
    PRODUCT P
JOIN
    PRODUCT_SUBCATEGORY PS
ON
    P.PRODUCT_SUBCATEGORY_ID = PS.PRODUCT_SUBCATEGORY_ID
JOIN
    PRODUCT_CATEGORY PC
ON
    PS.PRODUCT_CATEGORY_ID = PC.PRODUCT_CATEGORY_ID;
