-- Seleccionar campos para nueva tabla PRODUCT
-- Pendiente: PRODUCT ID y LOADING_DATE
SELECT
    P.NAME AS PRODUCT_NAME,
    P.COLOR AS PRODUCT_COLOR,
    PS.NAME AS PRODUCT_SUBCATEGORY,
    PC.NAME AS PRODUCT_CATEGORY
FROM
    ODS.PRODUCT P
    JOIN ODS.PRODUCT_SUBCATEGORY PS ON P.PRODUCT_SUBCATEGORY_ID = PS.PRODUCT_SUBCATEGORY_ID
    JOIN ODS.PRODUCT_CATEGORY PC ON PS.PRODUCT_CATEGORY_ID = PC.PRODUCT_CATEGORY_ID;

-- Seleccionar campos para nueva tabla EMPLOYEES
-- Pendiente: EMPLOYEE ID y LOADING_DATE
SELECT
    E.JOB_TITLE AS JOB_TITLE,
    D.GROUP_NAME AS GROUP_NAME,
    EP.RATE AS RATE,
    COUNT(*) AS QUANTITY
FROM
    ODS.EMPLOYEE E
    JOIN ODS.DEPARTMENT D ON E.ORGANIZATION_NODE = D.DEPARTMENT_ID
    JOIN ODS.EMPLOYEE_PAY_HISTORY EP ON E.BUSINESS_ENTITY_ID = EP.BUSINESS_ENTITY_ID
GROUP BY
    E.JOB_TITLE,
    D.GROUP_NAME,
    EP.RATE
ORDER BY
    E.JOB_TITLE;

-- Seleccionar campos para nueva tabla CUSTOMERS
-- Pendiente: CUSTOMERS_ID y LOADING_DATE
SELECT
    P.FIRST_NAME || ' ' || P.LAST_NAME AS CUSTOMER_NAME,
    EA.EMAIL_ADDRESS AS CUSTOMER_EMAIL,
    PP.PHONE_NUMBER AS CUSTOMER_PHONE,
    A.ADDRESS_LINE1 AS CUSTOMER_ADDRESS,
    A.CITY AS CUSTOMER_CITY,
    A.POSTAL_CODE AS CUSTOMER_POSTALCODE,
    SP.NAME AS CUSTOMER_STATE,
    CR.NAME AS CUSTOMER_COUNTRY
FROM
    ODS.PERSON P
    JOIN ODS.EMAIL_ADDRESS EA ON P.BUSINESS_ENTITY_ID = EA.BUSINESS_ENTITY_ID
    JOIN ODS.PERSON_PHONE PP ON P.BUSINESS_ENTITY_ID = PP.BUSINESS_ENTITY_ID
    JOIN ODS.ADDRESS A ON P.BUSINESS_ENTITY_ID = A.ADDRESS_ID
    JOIN ODS.STATE_PROVINCE SP ON A.STATE_PROVINCE_ID = SP.STATE_PROVINCE_ID
    JOIN ODS.COUNTRY_REGION CR ON SP.COUNTRY_REGION_CODE = CR.COUNTRY_REGION_CODE;