CREATE TABLE PARAMETROS.PARAMETROS (
    SISTEMA         VARCHAR2 (100 CHAR),
    NOMBRE_PARAM    VARCHAR2 (100 CHAR),
    VALOR_PARAM     VARCHAR2 (100 CHAR)
);

INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','HOSTNAME','localhost');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','DATABASENAME','orcl');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','PORTNUMBER','1521');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','SCHEMA','ODS');

INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','SCHEMA_DW','DATA_WAREHOUSE');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','DIR_FILE','C:\REPOSITORIO\OMEGA');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','USERNAME','ETL_USER');
    
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) 
    VALUES ('OMEGA','PASSWORD','etl_user');
COMMIT;

SELECT SISTEMA, NOMBRE_PARAM, VALOR_PARAM FROM PARAMETROS.PARAMETROS;