ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER PARAMETROS IDENTIFIED BY parametros;
CREATE USER USER_ETL IDENTIFIED BY user_etl;

GRANT ALL PRIVILEGES TO PARAMETROS;
GRANT ALL PRIVILEGES TO USER_ETL