ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER PARAMETROS IDENTIFIED BY parametros;
CREATE USER ODS IDENTIFIED BY ods;
CREATE USER ETL_USER IDENTIFIED BY etl_user;
CREATE USER DATA_WAREHOUSE IDENTIFIED BY dw;

GRANT ALL PRIVILEGES TO PARAMETROS;
GRANT ALL PRIVILEGES TO ODS;
GRANT ALL PRIVILEGES TO ETL_USER;
GRANT ALL PRIVILEGES TO DATA_WAREHOUSE;
