CREATE TABLE EMAIL_ADDRESS (
    EMAIL_ADDRESS_ID NUMBER PRIMARY KEY,
    BUSINESS_ENTITY_ID NUMBER,
    EMAIL_ADDRESS VARCHAR2(100 CHAR) UNIQUE,
    ROWGUID VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50 CHAR),
    GROUP_NAME VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);

CREATE TABLE EMPLOYEE (
  BUSINESS_ENTITY_ID NUMBER PRIMARY KEY,
  NATIONAL_ID_NUMBER VARCHAR2(20),
  LOGIN_ID VARCHAR2(50),
  ORGANIZATION_NODE VARCHAR2(50),
  ORGANIZATION_LEVEL NUMBER,
  JOB_TITLE VARCHAR2(50),
  BIRTH_DATE DATE,
  MARITAL_STATUS CHAR(1),
  GENDER CHAR(1),
  HIRE_DATE DATE,
  SALARIED_FLAG NUMBER(1),
  VACATION_HOURS NUMBER,
  SICK_LEAVE_HOURS NUMBER,
  CURRENT_FLAG NUMBER(1),
  ROW_GUID VARCHAR2(50 CHAR),
  MODIFIED_DATE DATE
);

CREATE TABLE EMPLOYEE_DEPARTMENT_HISTORY (
  BUSINESS_ENTITY_ID NUMBER,
  DEPARTMENT_ID NUMBER,
  SHIFT_ID NUMBER,
  START_DATE DATE,
  END_DATE DATE,
  MODIFIED_DATE DATE
);