CREATE TABLE EMAIL_ADDRESS (
    EMAIL_ADDRESS_ID NUMBER PRIMARY KEY,
    BUSINESS_ENTITY_ID NUMBER,
    EMAIL_ADDRESS VARCHAR2(100 CHAR) UNIQUE,
    ROWGUID VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50 CHAR),
    GROUP_NAME VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);