CREATE TABLE EMAIL_ADDRESS (
    EMAIL_ADDRESS_ID NUMBER PRIMARY KEY,
    BUSINESS_ENTITY_ID NUMBER,
    EMAIL_ADDRESS VARCHAR2(100 CHAR) UNIQUE,
    ROWGUID VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50 CHAR),
    GROUP_NAME VARCHAR2(50 CHAR),
    MODIFIED_DATE DATE
);

CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50 CHAR),
    ROWGUID RAW(16),
    MODIFIED_DATE DATE
);

CREATE TABLE PRODUCT_SUBCATEGORY (
    PRODUCT_SUBCATEGORY_ID NUMBER PRIMARY KEY,
    PRODUCT_CATEGORY_ID NUMBER,
    NAME VARCHAR2(50 CHAR),
    ROWGUID RAW(16),
    MODIFIED_DATE DATE,
    FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID)
);

CREATE TABLE STATE_PROVINCE (
    STATE_PROVINCE_ID NUMBER PRIMARY KEY,
    STATE_PROVINCE_CODE VARCHAR2(20 CHAR),
    COUNTRY_REGION_CODE VARCHAR2(20 CHAR),
    IS_ONLY_STATE_PROVINCE_FLAG NUMBER,
    NAME VARCHAR2(50 CHAR),
    TERRITORY_ID NUMBER,
    ROWGUID RAW(16),
    MODIFIED_DATE DATE
);
